version: '3.8'

services:
  backend:
    build: ./backend
    container_name: vpass_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/vpass
      - JWT_SECRET=vpass_super_secret_key_123
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - vpass_network

  frontend:
    build: ./frontend
    container_name: vpass_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - vpass_network

  mongo:
    image: mongo:6.0
    container_name: vpass_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - vpass_network

networks:
  vpass_network:
    driver: bridge

volumes:
  mongo_data:
